Add support for reactive in the server extension
quarkiverse/quarkus-openapi-generator pull request #731
Opened 2024-06-12 09:03 UTC by carlesarnal

Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [ ] Pull Request contains link to the issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
This PR introduces support for generating reactive code using the server extension
</summary>

2024-06-12 13:31 UTC, ricardozanini approved these changes

2024-06-12 20:54 UTC, hbelmiro requested changes
Thank you @carlesarnal.

It seems like you're confusing the new dependencies for the classic and reactive implementations.
See https://quarkus.io/guides/rest-migration#dependencies.

RESTEasy Classic is still known as RESTEasy (quarkus-resteasy)
RESTEasy Reactive now is Quarkus REST (quarkus-rest).

I suggested changes to the `pom.xml` files.

-----

I also suggest using Maven Profiles to avoid test duplication. With that, you can have just one module and set a flag to run them with each profile (classic or reactive).
[We do that in the client module](https://github.com/quarkiverse/quarkus-openapi-generator/blob/7a255ddc778661e1010d0a679ebbe24f735e2a73/client/integration-tests/pom.xml#L93).

That's all you need since all the tests are identical for both implementations.
In case we need specific tests for each implementation in the future, we can use the `org.junit.jupiter.api.Tag`, like we did [here](https://github.com/quarkiverse/quarkus-openapi-generator/blob/7a255ddc778661e1010d0a679ebbe24f735e2a73/client/integration-tests/config-key/src/test/java/io/quarkiverse/openapi/generator/configkey/QuarkusConfigKeyOpenApiTest.java#L18).

Our CI already handles both profiles. See, for example, [the job for the reactive profile](https://github.com/quarkiverse/quarkus-openapi-generator/blob/7a255ddc778661e1010d0a679ebbe24f735e2a73/.github/workflows/build.yml#L75).

2024-06-12 20:54 UTC, hbelmiro commented on server/integration-tests/reactive/pom.xml
> +            <artifactId>quarkus-resteasy-reactive</artifactId>
```suggestion
            <artifactId>quarkus-rest</artifactId>
```

2024-06-12 20:54 UTC, hbelmiro commented on server/integration-tests/reactive/pom.xml
> +    <artifactId>quarkus-openapi-generator-server-integration-tests-resteasy-reactive</artifactId>
```suggestion
    <artifactId>quarkus-openapi-generator-server-integration-tests-quarkus-rest</artifactId>
```

2024-06-12 20:54 UTC, hbelmiro commented on server/integration-tests/reactive/pom.xml
> +            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
```suggestion
            <artifactId>quarkus-rest-jackson</artifactId>
```

2024-06-12 20:54 UTC, hbelmiro commented on server/integration-tests/resteasy/pom.xml
> +            <artifactId>quarkus-rest</artifactId>
```suggestion
            <artifactId>quarkus-resteasy</artifactId>
```

2024-06-12 20:54 UTC, hbelmiro commented on server/integration-tests/resteasy/pom.xml
> +            <artifactId>quarkus-rest-jackson</artifactId>
```suggestion
            <artifactId>quarkus-resteasy-jackson</artifactId>
```

2024-06-13 09:54 UTC, carlesarnal commented
> Thank you @carlesarnal.
> 
> It seems like you're confusing the new dependencies for the classic and reactive implementations. See https://quarkus.io/guides/rest-migration#dependencies.
> 
> RESTEasy Classic is still known as RESTEasy (quarkus-resteasy) RESTEasy Reactive now is Quarkus REST (quarkus-rest).
> 
> I suggested changes to the `pom.xml` files.
> 
> I also suggest using Maven Profiles to avoid test duplication. With that, you can have just one module and set a flag to run them with each profile (classic or reactive). [We do that in the client module](https://github.com/quarkiverse/quarkus-openapi-generator/blob/7a255ddc778661e1010d0a679ebbe24f735e2a73/client/integration-tests/pom.xml#L93).
> 
> That's all you need since all the tests are identical for both implementations. In case we need specific tests for each implementation in the future, we can use the `org.junit.jupiter.api.Tag`, like we did [here](https://github.com/quarkiverse/quarkus-openapi-generator/blob/7a255ddc778661e1010d0a679ebbe24f735e2a73/client/integration-tests/config-key/src/test/java/io/quarkiverse/openapi/generator/configkey/QuarkusConfigKeyOpenApiTest.java#L18).
> 
> Our CI already handles both profiles. See, for example, [the job for the reactive profile](https://github.com/quarkiverse/quarkus-openapi-generator/blob/7a255ddc778661e1010d0a679ebbe24f735e2a73/.github/workflows/build.yml#L75).

Tests are not exactly identical (the test class is). There are two different implementations in the Java projects one [reactive](https://github.com/quarkiverse/quarkus-openapi-generator/pull/731/files#diff-e47e71d7fe34b0209c2b2748505c2136ce29c0c92e850493527ac592e57b4b61) and another [non-reactive](https://github.com/quarkiverse/quarkus-openapi-generator/pull/731/files#diff-9049dfd83f1a69611f7d7113500e744ef2f9409b00d842d3a4643e117ac68861), and, if I merge them both into a single module, it will fail. I can make the tests use profiles to align with the rest of the project, but I don't think it's feasible to merge both modules.

2024-06-13 20:34 UTC, hbelmiro approved these changes
@carlesarnal I see. I don't see a benefit in using profiles then.

2024-06-13 20:34 UTC, merged