Remove operation id prefix
quarkiverse/quarkus-openapi-generator pull request #865
Opened 2024-11-21 23:36 UTC by yuhaibohotmail

Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [x]  You have read the [contributors guide](CONTRIBUTING.md)
- [x]  Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [x]  Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [ ] Pull Request contains link to the issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x]  Pull Request does not include fixes for issues other than the main ticket

When use smallrye openapi operationid strategy CLASS_METHOD,operationId fields take the form of "class_name_method". For example, "User_findAll".

In this PR, we add a config properties remove-operation-id-prefix,to delete class name from operationId.

2024-11-22 11:52 UTC, fjtirado approved these changes

2024-11-22 16:50 UTC, ricardozanini requested changes
I need help finding what this PR is doing. I'm only seeing an introduction of a property to the generator. What do you do with it after? Or is this something that the underlying generator already takes care of? If so, please add a reference.
Can you also please add some tests under the `integration-tests` module?

2024-11-24 23:54 UTC, yuhaibohotmail commented on client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
> +import static io.quarkiverse.openapi.generator.deployment.CodegenConfig.ConfigName.*;
Already corrected.

2024-11-24 23:55 UTC, yuhaibohotmail commented on docs/modules/ROOT/pages/includes/getting-started.adoc
> +You can customize the name of generated method. To do that, you must define the following properties:
we add a config properties remove-operation-id-prefix,to delete class name from operationId. The properties are passed to the openapi-generator, and the specific functions are executed by the openapi-generator.

2024-11-24 23:59 UTC, yuhaibohotmail commented
> I need help finding what this PR is doing. I'm only seeing an introduction of a property to the generator. What do you do with it after? Or is this something that the underlying generator already takes care of? If so, please add a reference. Can you also please add some tests under the `integration-tests` module?

Thanks for the review.
I only add the property , the functions are executed by the openapi-generator.
This is a function of openapi-generator. Do I need to write an integration test?

2024-11-26 15:10 UTC, ricardozanini commented
@yuhaibohotmail, thanks for clarifying it. You can use the `deployment` module tests to test it or add a new `integration-test` module.

2024-11-27 07:07 UTC, yuhaibohotmail commented
> @yuhaibohotmail, thanks for clarifying it. You can use the `deployment` module tests to test it or add a new `integration-test` module.
@ricardozanini , we have the new `integration-test` module.

2024-11-27 13:13 UTC, closed without merging