remove operation id prefix
quarkiverse/quarkus-openapi-generator pull request #873
Opened 2024-11-27 14:56 UTC by yuhaibohotmail

You have read the [contributors guide](https://github.com/quarkiverse/quarkus-openapi-generator/pull/CONTRIBUTING.md)
 Your code is properly formatted according to [our code style](https://github.com/quarkiverse/quarkus-openapi-generator/pull/CONTRIBUTING.md#code-style)
 Pull Request title contains the target branch if not targeting main: [0.9.x] Subject
 Pull Request contains link to the issue
 Pull Request contains link to any dependent or related Pull Request
 Pull Request contains description of the issue
 Pull Request does not include fixes for issues other than the main ticket
Fix https://github.com/quarkiverse/quarkus-openapi-generator/issues/866

When use smallrye openapi operationid strategy CLASS_METHOD,operationId fields take the form of "class_name_method". For example, "User_findAll". We want remove operationId prefix (e.g. User_findAll=> findAll)

In this PR, we add a config properties remove-operation-id-prefix,to delete class name from operationId. The properties are passed to the openapi-generator, and the specific functions are executed by the openapi-generator.

https://github.com/OpenAPITools/openapi-generator/blob/4c5a57fe7bae59483bb8fa9218be8dc4f82e1bda/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L5638

You have read the [contributors guide](https://github.com/quarkiverse/quarkus-openapi-generator/pull/CONTRIBUTING.md)
 Your code is properly formatted according to [our code style](https://github.com/quarkiverse/quarkus-openapi-generator/pull/CONTRIBUTING.md#code-style)
 Pull Request title contains the target branch if not targeting main: [0.9.x] Subject
 Pull Request contains link to the issue
 Pull Request contains link to any dependent or related Pull Request
 Pull Request contains description of the issue
 Pull Request does not include fixes for issues other than the main ticket
Fix https://github.com/quarkiverse/quarkus-openapi-generator/issues/866

When use smallrye openapi operationid strategy CLASS_METHOD,operationId fields take the form of "class_name_method". For example, "User_findAll". We want remove operationId prefix (e.g. User_findAll=> findAll)

In this PR, we add a config properties remove-operation-id-prefix,to delete class name from operationId. The properties are passed to the openapi-generator, and the specific functions are executed by the openapi-generator.

https://github.com/OpenAPITools/openapi-generator/blob/4c5a57fe7bae59483bb8fa9218be8dc4f82e1bda/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L5638

2024-11-27 14:59 UTC, yuhaibohotmail commented
@ricardozanini   @ricardozanini 
Sorry I messed up my commit, so I rebuilt this PR.

2024-11-27 15:08 UTC, ricardozanini approved these changes
It's an unusual use case; many thanks for bringing this to our attention and sending the PR. 

Now, with the test, it makes much more sense.

2024-11-28 12:05 UTC, hbelmiro requested changes

2024-11-28 12:05 UTC, hbelmiro commented on client/integration-tests/remove-operationid-prefix/src/test/java/io/quarkiverse/openapi/generator/it/RemoveOperatiionIdPrefixTest.java
> +public class RemoveOperatiionIdPrefixTest {
Typo.

```suggestion
public class RemoveOperationIdPrefixTest {
```

2024-11-28 12:05 UTC, hbelmiro commented on client/integration-tests/remove-operationid-prefix/src/test/java/io/quarkiverse/openapi/generator/it/RemoveOperatiionIdPrefixTest.java
> +    void apiIsBeingGenerated() throws NoSuchMethodException {
```suggestion
    void apiIsBeingGenerated() {
```

2024-11-28 14:12 UTC, hbelmiro approved these changes

2024-11-28 17:50 UTC, hbelmiro approved these changes

2024-11-29 15:48 UTC, merged